[package]
name = "git-tcr"
edition = "2021"
version = "0.1.0"

[dependencies]
serde = { version = "1.0.197", features = ["derive"] }
serde_yaml = "0.9.32"
clap = { version = "4.5.4", features = ["derive"] }
