[package]
name = "git-tcr"
edition = "2021"
version = "1.0.0"

[dependencies]
clap = { version = "4.5.35", features = ["derive"] }
serde = { version = "1.0.197", features = ["derive"] }
serde_yaml = "0.9.32"
notify = "8.0.0"
notify-debouncer-full = "0.5.0"
