name: Rust

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test
        run: cargo test --verbose

  release:
    needs: test
    strategy:
      matrix:
        target: [ aarch64-apple-darwin ]
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: cargo build --release --target ${{ matrix.target }}
      - name: Upload Release Asset
        uses: actions/upload-artifact@v4
        with:
          name: 'git-tcr-${{ matrix.target }}'
          path: 'target/${{ matrix.target }}/release/*'

